FROM maven:3.9.0-amazoncorretto-17
ARG TOOLMASTER_USERS_SERVICE_PORT

WORKDIR /app
COPY . .

CMD mvn exec:java -Dexec.mainClass="edu.puj.toolmaster.users.UsersServiceApplication"

EXPOSE ${TOOLMASTER_USERS_SERVICE_PORT}
